"""Tests for recursive summarization at memory rehydration."""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any

from opencontext_core.memory.rehydration import summarize_to_budget


class _Gateway:
    def __init__(self, content: str, provider: str = "host") -> None:
        self._content = content
        self._provider = provider
        self.calls = 0

    def generate(self, request: Any) -> Any:
        self.calls += 1
        return SimpleNamespace(content=self._content, provider=self._provider)


def test_fits_budget_is_noop_without_calling_model() -> None:
    gw = _Gateway("should not be used")
    text = "- small memory line"
    assert summarize_to_budget(text, target_tokens=1000, gateway=gw) == text
    assert gw.calls == 0  # no model call when it already fits


def test_real_model_summary_is_used() -> None:
    big = "\n".join(f"- decision {i}: keep file src/mod{i}.py" for i in range(400))
    gw = _Gateway("- condensed: keep src/mod*.py decisions", provider="host")
    out = summarize_to_budget(big, target_tokens=50, gateway=gw)
    assert out == "- condensed: keep src/mod*.py decisions"
    assert gw.calls == 1


def test_mock_model_falls_back_to_deterministic_trim() -> None:
    big = "\n".join(f"- line {i}" for i in range(400))
    gw = _Gateway("Mock response generated by OpenContext", provider="mock")
    out = summarize_to_budget(big, target_tokens=50, gateway=gw)
    # Mock output is rejected -> deterministic trim, which keeps the first lines.
    assert "Mock response" not in out
    assert out.startswith("- line 0")
    assert len(out) < len(big)


def test_no_gateway_falls_back_to_trim() -> None:
    big = "\n".join(f"- line {i}" for i in range(400))
    out = summarize_to_budget(big, target_tokens=50, gateway=None)
    assert "Mock" not in out
    assert out.startswith("- line 0")
    assert len(out) < len(big)
