"""CI check CLI commands."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from opencontext_core.dx.console_styles import console
from opencontext_core.quality.ci_checks import CheckRunner

CONTEXTBENCH_WORKFLOW = """\
# OpenContext ContextBench CI
# Auto-generated by `opencontext ci-check init`
name: OpenContext ContextBench

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  contextbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenContext
        run: pip install opencontext-cli
      - name: Initialize checks
        run: opencontext ci-check init
      - name: Run ContextBench checks
        run: opencontext ci-check run --json > contextbench-report.json
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: contextbench-report
          path: contextbench-report.json
      - name: Fail on errors
        run: |
          python3 -c "
          import json
          with open('contextbench-report.json') as f:
              report = json.load(f)
          summary = report.get('summary', {})
          if summary.get('failed', 0) > 0:
              print('❌ ContextBench checks failed')
              exit(1)
          print('✅ All ContextBench checks passed')
          "
"""


def add_ci_check_parser(subparsers: Any) -> None:
    """Add ci-check command parsers."""
    # Visible in --help: `opencontext status` tells users to run
    # `opencontext ci-check init`, so the command must be discoverable.
    check_parser = subparsers.add_parser("ci-check", help="Manage CI context checks.")
    check_sub = check_parser.add_subparsers(dest="ci_check_command", required=True)
    check_init = check_sub.add_parser(
        "init", help="Initialize checks directory and ContextBench workflow."
    )
    check_init.add_argument(
        "--no-workflow", action="store_true", help="Skip GitHub Actions workflow generation."
    )
    check_sub.add_parser("list", help="List discovered checks.")
    check_run = check_sub.add_parser("run", help="Run all checks.")
    check_run.add_argument("--file", help="Run on specific file only.")
    check_run.add_argument("--json", action="store_true")
    check_run.add_argument(
        "--no-refresh",
        action="store_true",
        help="Use the existing pinned index for the contextbench gate (CI fast path).",
    )
    check_run.add_argument(
        "--suite",
        default="examples/evals/contextbench.yaml",
        help="ContextBench suite for the efficiency/parity gate.",
    )
    check_create = check_sub.add_parser("create", help="Create a new check template.")
    check_create.add_argument("name", help="Check name.")
    check_create.add_argument("--description", default="", help="Check description.")
    check_gh = check_sub.add_parser(
        "github-actions", help="Generate ContextBench GitHub Actions workflow."
    )
    check_gh.add_argument("--force", action="store_true", help="Overwrite existing workflow file.")


def handle_ci_check(args: Any) -> None:
    """Handle ci-check commands."""
    command = args.ci_check_command
    name = getattr(args, "name", None)
    file = getattr(args, "file", None)
    json_output = getattr(args, "json", False)

    runner = CheckRunner()

    if command == "init":
        path = runner.init_checks_directory()
        console.success(f"Initialized checks directory: {path}")
        skip_workflow = getattr(args, "no_workflow", False)
        if not skip_workflow:
            workflow_path = _generate_contextbench_workflow()
            console.success(f"Generated ContextBench workflow: {workflow_path}")
    elif command == "github-actions":
        force = getattr(args, "force", False)
        workflow_path = Path(".github/workflows/opencontext-contextbench.yml")
        if workflow_path.exists() and not force:
            console.warning(f"Workflow already exists: {workflow_path}. Use --force to overwrite.")
            return
        _write_contextbench_workflow(workflow_path)
        console.success(f"Generated ContextBench workflow: {workflow_path}")
    elif command == "list":
        checks = runner.discover_checks()
        if json_output:
            data = [
                {"name": c.name, "description": c.description, "severity": c.severity.value}
                for c in checks
            ]
            print(json.dumps(data, indent=2))
        else:
            console.header("CI Checks")
            if not checks:
                console.dim("No checks found. Run 'opencontext ci-check init'")
            else:
                console.table(
                    "Discovered Checks",
                    ["Name", "Severity", "Description"],
                    [[c.name, c.severity.value, c.description] for c in checks],
                )
    elif command == "run":
        files = [file] if file else None
        if json_output:
            # No spinner: console.progress writes cursor/ANSI control codes to stdout,
            # which would corrupt the machine-readable JSON the workflow YAML parses.
            results = runner.run_all_checks(files)
        else:
            with console.progress("Running checks...") as progress:
                task = progress.add_task("Running checks...", total=None)
                results = runner.run_all_checks(files)
                progress.update(task, completed=True)
        # Fold the native architecture/code-quality evaluation into the run so
        # `ci-check run` actually surfaces it (one engine, shared CheckResult schema).
        from opencontext_core.quality.ci_checks import (
            ARCHITECTURE_CHECK_NAME,
            architecture_check_results,
        )

        results[ARCHITECTURE_CHECK_NAME] = architecture_check_results(runner.project_path, files)
        report = runner.generate_report(results)
        _attach_contextbench(report, args)
        if json_output:
            print(json.dumps(report, indent=2))
        else:
            _display_check_report(report)
    elif command == "create" and name:
        template = runner.create_check_template(name, "Custom check")
        console.print(template)
    else:
        console.error(f"Unknown ci-check command: {command}")


def _display_check_report(report: dict[str, Any]) -> None:
    """Display a formatted check report."""
    summary = report.get("summary", {})
    total = summary.get("total_checks", 0)
    passed = summary.get("passed", 0)
    failed = summary.get("failed", 0)
    warnings = summary.get("warnings", 0)
    errors = summary.get("errors", 0)
    success = summary.get("success", False)

    console.header("Check Report")

    if success:
        console.success(f"All {total} checks passed")
    else:
        console.error(f"{failed}/{total} checks failed")

    console.table(
        "Summary",
        ["Metric", "Count"],
        [
            ["Total", str(total)],
            ["Passed", str(passed)],
            ["Failed", str(failed)],
            ["Warnings", str(warnings)],
            ["Errors", str(errors)],
        ],
    )

    failed_results = [r for r in report.get("results", []) if r["status"] != "passed"]
    if failed_results:
        console.section("Failed Checks")
        for r in failed_results:
            severity_color = "#FF6F91" if r["severity"] in ("error", "critical") else "#FFC75F"
            msg = f"  [bold {severity_color}]{r['severity'].upper()}[/]"
            msg += f" {r['check']}: {r['message']}"
            console.print(msg)
            if r.get("file"):
                console.print(f"    [dim]File: {r['file']}:{r.get('line', 'N/A')}[/]")
            if r.get("suggestion"):
                console.print(f"    [dim]Suggestion: {r['suggestion']}[/]")


def _attach_contextbench(report: dict[str, Any], args: Any) -> None:
    """Fold the honest efficiency benchmark into the CI report (gates on parity).

    D-CI: the contextbench CI path gates on QUALITY-PARITY only — any case whose CON
    pack misses an expected source or hits a forbidden one counts as a failure and is
    added to ``summary.failed`` (so the existing ``failed > 0`` workflow gate trips).
    The measured ``{tokens, tool_calls, latency}`` deltas are reported as
    informational numbers; there is NO reduction threshold and NO claim field. If the
    suite or index is unavailable, the section is marked skipped rather than crashing
    the pipeline.
    """
    suite_path = Path(getattr(args, "suite", "examples/evals/contextbench.yaml"))
    summary = report.setdefault("summary", {})
    if not suite_path.exists():
        report["contextbench"] = {"status": "skipped", "reason": f"no suite at {suite_path}"}
        return
    try:
        from opencontext_core.evaluation.efficiency import EfficiencyBenchmark
        from opencontext_core.evaluation.evaluator import load_context_bench_cases
        from opencontext_core.runtime import OpenContextRuntime

        config_path = getattr(args, "config", None)
        resolved = Path(config_path) if config_path else None
        runtime = OpenContextRuntime(
            config_path=str(resolved) if resolved and resolved.exists() else None,
        )
        cases = load_context_bench_cases(suite_path)
        refresh = not getattr(args, "no_refresh", False)
        efficiency = EfficiencyBenchmark(runtime, root=getattr(args, "root", "."))
        result = efficiency.evaluate_suite(cases, refresh_index=refresh)
    except Exception as exc:  # CI resilience: surface, do not crash the gate.
        report["contextbench"] = {"status": "error", "reason": str(exc)}
        return

    report["contextbench"] = {
        "status": "ok",
        "cases": [
            {
                "case_id": c.case_id,
                "con_sufficient": c.con_sufficient,
                "con": c.con.model_dump(mode="json"),
                "sin": c.sin.model_dump(mode="json"),
                "token_delta": c.token_delta,
                "tool_call_delta": c.tool_call_delta,
            }
            for c in result.cases
        ],
        "median_token_delta": result.median_token_delta,
        "median_tool_call_delta": result.median_tool_call_delta,
        "insufficient_cases": result.insufficient_cases,
        "all_sufficient": result.all_sufficient,
    }
    # Gate: parity-insufficient cases add to the failure count.
    insufficient = result.insufficient_cases
    if insufficient:
        summary["failed"] = int(summary.get("failed", 0)) + insufficient
        summary["success"] = False


def _generate_contextbench_workflow() -> Path:
    """Generate the ContextBench GitHub Actions workflow as part of init."""
    workflow_path = Path(".github/workflows/opencontext-contextbench.yml")
    _write_contextbench_workflow(workflow_path)
    return workflow_path


def _write_contextbench_workflow(workflow_path: Path) -> None:
    """Write the ContextBench workflow file."""
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(CONTEXTBENCH_WORKFLOW)
