"""Render the eight curated ``.opencontext/memory/*.md`` project-memory files.

Book OC-MEMORY-001 §16: the markdown files are *projections* of the store, not an
editable source of truth, so they are regenerated (overwritten) from records on
demand. Each file selects a slice of the store and renders content + evidence +
status so a human (or another agent) can read the curated memory at a glance.
"""

from __future__ import annotations

from pathlib import Path

from opencontext_core.models.agent_memory import MemoryLayer, MemoryRecord

# The eight book files, in render order. Exported so layout/CLI can reference them.
PROJECT_MEMORY_FILES: tuple[str, ...] = (
    "project-profile.md",
    "conventions.md",
    "decisions.md",
    "commands.md",
    "failure-patterns.md",
    "owners.md",
    "environment.md",
    "harness-learnings.md",
)

_TITLES: dict[str, str] = {
    "project-profile.md": "Project Profile",
    "conventions.md": "Conventions",
    "decisions.md": "Decisions",
    "commands.md": "Commands",
    "failure-patterns.md": "Failure Patterns",
    "owners.md": "Owners",
    "environment.md": "Environment",
    "harness-learnings.md": "Harness Learnings",
}


def _has_kind(record: MemoryRecord, kind: str) -> bool:
    return f"kind:{kind}" in record.tags


def _has_tag(record: MemoryRecord, tag: str) -> bool:
    return tag in record.tags or any(t.split(":", 1)[0] == tag for t in record.tags)


def _select(records: list[MemoryRecord], filename: str) -> list[MemoryRecord]:
    """Choose the records that belong in a given projection file."""
    if filename == "project-profile.md":
        return [r for r in records if r.layer == MemoryLayer.PROJECT]
    if filename == "conventions.md":
        return [r for r in records if _has_kind(r, "constraint")]
    if filename == "decisions.md":
        return [r for r in records if _has_kind(r, "decision")]
    if filename == "commands.md":
        return [r for r in records if r.layer == MemoryLayer.PROCEDURAL]
    if filename == "failure-patterns.md":
        return [
            r for r in records if r.layer in (MemoryLayer.FAILURE, MemoryLayer.HARNESS_EXPERIENCE)
        ]
    if filename == "owners.md":
        return [r for r in records if _has_tag(r, "owner") or r.scope == "team"]
    if filename == "environment.md":
        return [r for r in records if _has_tag(r, "env") or _has_tag(r, "environment")]
    if filename == "harness-learnings.md":
        return [r for r in records if r.layer == MemoryLayer.HARNESS_EXPERIENCE]
    return []


def _render_record(record: MemoryRecord) -> str:
    evidence = ", ".join(ref.source for ref in record.source_refs) or "—"
    return (
        f"- {record.content.strip()}\n"
        f"  - status: {record.status.value} | confidence: {record.confidence:.2f}\n"
        f"  - evidence: {evidence}\n"
    )


def _render_file(filename: str, records: list[MemoryRecord]) -> str:
    title = _TITLES[filename]
    banner = "<!-- Generated by `opencontext memory maintain`. Do not edit. -->"
    lines = [f"# {title}", "", banner, ""]
    if not records:
        lines.append("_No records yet._")
        lines.append("")
        return "\n".join(lines)
    for record in records:
        lines.append(_render_record(record).rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def _all_records(store: object, *, limit: int) -> list[MemoryRecord]:
    lister = getattr(store, "list_records", None)
    if callable(lister):
        try:
            return list(lister(limit=limit))
        except Exception:
            return []
    return []


def generate(store: object, root: Path | str, *, limit: int = 500) -> list[Path]:
    """Render all eight project-memory files under ``<root>/.opencontext/memory/``.

    Overwrites existing files (they are projections). Returns the written paths.
    """
    base = Path(root) / ".opencontext" / "memory"
    base.mkdir(parents=True, exist_ok=True)
    records = _all_records(store, limit=limit)
    written: list[Path] = []
    for filename in PROJECT_MEMORY_FILES:
        selected = _select(records, filename)
        path = base / filename
        path.write_text(_render_file(filename, selected), encoding="utf-8")
        written.append(path)
    return written
