"""Deterministic mock gateway for tests and local development."""

from __future__ import annotations

from opencontext_core.context.budgeting import estimate_tokens
from opencontext_core.models.llm import LLMRequest, LLMResponse


class MockLLMGateway:
    """Mock LLM gateway that never calls external services."""

    def generate(self, request: LLMRequest) -> LLMResponse:
        """Return a deterministic response for a request."""

        first_line = request.prompt.splitlines()[0] if request.prompt.splitlines() else ""
        answer = (
            "Mock response generated by OpenContext Runtime. "
            f"Provider={request.provider} model={request.model}. "
            f"Context items={len(request.context_items)}. Prompt starts with: {first_line[:80]}"
        )
        return LLMResponse(
            content=answer,
            provider=request.provider,
            model=request.model,
            input_tokens=estimate_tokens(request.system_prompt + request.prompt),
            output_tokens=estimate_tokens(answer),
            metadata={"mock": True, "system_prompt": request.system_prompt},
        )
